### ISSUE TITLE
Something wrong in the environment

### ISSUE THREAD

**Issue by Qinghongye** [wengflow/robust-e-nerf#1]
The work is awesome,but I meet some problems.
D:\Githubproject\robust-e-nerf>conda env create -f environment.yml             
Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound:
  - cudatoolkit-dev=11.3.1
 It seems that there is no package called "cudatoolkit-dev " in these channels:
  - pytorch
  - nvidia
  - conda-forge
  - robostack
  - defaults

**Comment by wengflow** [comment]
Thanks for the interest in our work!
From what you have shown me, I believe this is due to Windows. Specifically, the [`cudatoolkit-dev=11.3.1` package from `conda-forge`](https://anaconda.org/conda-forge/cudatoolkit-dev/files?version=11.3.1) isn't compiled for `win-64`. You may try to manually install CUDA Toolkit 11.3.1 on your Windows machine, or create the environment in Linux or a Docker container.

**Comment by Qinghongye** [comment]
Thank you for your solution！I will try soon!



---- Replied Message ----
| From | Weng Fei ***@***.***> |
| Date | 10/17/2023 12:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [wengflow/robust-e-nerf] Something wrong in the environment (Issue #1) |

Thanks for the interest in our work!
From what you have shown me, I believe this is due to Windows. Specifically, the cudatoolkit-dev=11.3.1 package from conda-forge isn't compiled for win-64. You may try to manually install CUDA Toolkit 11.3.1 on your Windows machine, or create the environment in Linux or a Docker container.
