### ISSUE TITLE
Dataset download failed.

### ISSUE THREAD

**Issue by azhuantou** [wengflow/robust-e-nerf#4]
Hi! @wengflow 
Thanks for your great work!

When I download the synthetic dataset using "git lfs", it got stuck as shown in the figure below.
Would you mind uploading the dataset to BaiduYun Drive or Google Drive?

![(HGKRR{B09UE$1{FT%M@BY3](https://github.com/wengflow/robust-e-nerf/assets/33474693/6ba96995-beb0-4f8e-b4a0-dde109f9c57b)

**Comment by wengflow** [comment]
Hi @azhuantou!

Did you follow the exact setup instructions listed [here](https://huggingface.co/datasets/wengflow/robust-e-nerf#setup)?
I'm afraid I'm not able to upload the dataset elsewhere, since the dataset is rather huge. But a workaround is to download each git LFS file manually via the dataset repo on Hugging Face, e.g. `chair/easy/esim.bag` as attached.

<img width="2202" alt="image" src="https://github.com/wengflow/robust-e-nerf/assets/116507898/4b87fd15-f9f0-4454-b35b-49f0e30c44b4">

**Comment by azhuantou** [comment]
Thanks for your reply! @wengflow 

I followed the instruction strictly, but it failed, possibly due to the special network conditions in CN. Additionally, I tried to download each LFS file manually, but there are too many files to click on.

![%GQ2U TSYD4)ZTC$V_DIV(C](https://github.com/wengflow/robust-e-nerf/assets/33474693/1f296a5d-7218-4082-b3ff-c576fa8ea962)

**Comment by azhuantou** [comment]
I solved this problem in another way. Thanks for your timely reply.

**Comment by gaojianzhen** [comment]
> 我用另一种方法解决了这个问题。谢谢你的及时回复。
你好，请问您是怎么解决的
